# RUN: python3 %s

import numpy as np
import onnxruntime as ort
import subprocess
import os

def verify_fused_matmul(onnx_path, m, n, k):
    # A [m x k], B [k x n], Bias [m x n]
    a = np.random.randn(m, k).astype(np.float32)
    b = np.random.randn(k, n).astype(np.float32)
    bias = np.random.randn(m, n).astype(np.float32)

    a.tofile("a.bin")
    b.tofile("b.bin")
    bias.tofile("bias.bin")

    # Get ORT Ground Truth
    sess = ort.InferenceSession(onnx_path)
    expected = sess.run(None, {
        'X': a,
        'Y': b,
        'Bias': bias
    })[0]

    # Run
    driver_path = "../../build/driver"
    stages = ["mlir", "mlir-tensor", "mlir-memref", "mlir-llvm", "llvm"]

    # Configs
    configs = [
        {"label": "naive", "tiling": False, "transpose": False, "active": True},
        {"label": "transposed", "tiling": False, "transpose": True, "active": True},
        {"label": "tiled_fused_transposed", "tiling": True, "transpose": True, "active": True}
    ]

    performance_results = {}

    for cfg in configs:
        if not cfg.get("active", True):
            print(f"\nSkipping {cfg['label'].upper()} (disabled)...")
            continue

        prefix = cfg["label"]
        print(f"\n" + "="*50)
        print(f"PROCESSING CONFIG: {prefix.upper()}")
        print("="*50)

        input_files_arg = "-input-files=a.bin,b.bin,bias.bin"

        # Build common flags list once per config
        common_flags = []
        if cfg.get("tiling"): common_flags.append("-tiling")
        if cfg.get("transpose"): common_flags.append("-transpose")

        # Capture IR for all stages
        for stage in stages:
            ext = "ll" if stage == "llvm" else "mlir"
            ir_filename = f"{prefix}_{stage}.{ext}"

            cmd = [driver_path, onnx_path, f"-emit={stage}", input_files_arg] + common_flags

            print(f"Capturing stage: {stage} -> {ir_filename}")

            try:
                result = subprocess.run(cmd, capture_output=True, text=True, check=True)
                with open(ir_filename, "w") as f:
                    f.write(result.stdout)
            except subprocess.CalledProcessError as e:
                print(f"Error during stage{stage}: {e.stderr}")

        # Run JIT (regular)
        print(f"Launching JIT for {prefix}")
        jit_cmd = [driver_path, onnx_path, "-emit=jit", input_files_arg] + common_flags
        jit_proc = subprocess.run(jit_cmd, capture_output=True, text=True, check=True)

        # Run JIT (with Valgrind)
        # print(f"Launching JIT (with Cachegrind) for {prefix}")
        # cache_out_file = f"cachegrind_{prefix}.out"
        # valgrind_prefix = [
        #     "valgrind",
        #     "--tool=cachegrind",
        #     f"--cachegrind-out-file={cache_out_file}",
        #     # --CacheLevel=notActualSize(actualsize),Associativity,LineSize
        #     "--I1=131072,8,128",     # Instruction L1: 128KB (192KB), 8-way, 128B line
        #     "--D1=131072,8,128",     # Data L1: 128KB, 8-way, 128B line
        #     "--LL=16777216,16,128"   # Last Level (L2): 16MB (12MB), 12-way, 128B line
        # ]

        # jit_cmd = valgrind_prefix + [driver_path, onnx_path, "-emit=jit", input_files_arg] + common_flags
        # jit_proc = subprocess.run(jit_cmd, capture_output=True, text=True)

        # Parse Math Time from output
        for line in jit_proc.stdout.split('\n'):
            if "Actual Math Time:" in line:
                print(f"TIMING: {line.strip()}")
                performance_results[prefix] = line.split(":")[1].strip()

        # Load JIT result
        if not os.path.exists("output.bin"):
            print("Error: output.bin was not generated by the driver.")
            return

        actual = np.fromfile("output.bin", dtype=np.float32)

        if actual.size != expected.size:
            print(f"Error: Size mismatch. Expected {expected.size}, got {actual.size}")
            return

        actual = actual.reshape(expected.shape)

        # Compare elements
        max_diff = np.max(np.abs(actual - expected))
        print("-" * 30)
        print(f"Expected (ORT): {expected.flatten()[:7]}")
        print(f"Actual (JIT): {actual.flatten()[:7]}")

        if max_diff == 0:
            print("RESULT: 100% Bit-Identical Match")
        elif max_diff < 1e-5:
            print(f"RESULT: Perfect Pass (Max Diff): {max_diff:.2e}")
        elif max_diff < 1e-3:
            print(f"RESULT: Acceptable Accumulation Error (Max Diff: {max_diff:.2e})")
        else:
            print(f"RESULT: FAILURE (Max Diff: {max_diff:.2e})")
        print("-"*30)

    # Summary
    print("\nSUMMARY: ")
    for label, timing in performance_results.items():
        print(f"{label}: {timing}")

verify_fused_matmul("../../models/onnx_files/fused_matmul_512.onnx", 512, 512, 512)