# RUN: python3 %s

import numpy as np
import onnxruntime as ort
import subprocess
import os

def verify_matmul(onnx_path, m, n, k):
    # Generate data
    a = np.random.randn(m, k).astype(np.float32)
    b = np.random.randn(k, n).astype(np.float32)

    # Save to binary
    a.tofile("a.bin")
    b.tofile("b.bin")

    # Get ORT Ground Truth
    sess = ort.InferenceSession(onnx_path)
    input_names = [i.name for i in sess.get_inputs()]
    expected = sess.run(None, {input_names[0]: a, input_names[1]: b})[0]

    # Run
    driver_path = "../../build/driver"
    stages = ["mlir", "mlir-tensor", "mlir-memref", "mlir-llvm", "llvm"]

    # Configs to compare
    configs = [
        {"label": "standard", "tiling": True, "transpose": False, "active": True},
        {"label": "transposed", "tiling": True, "transpose": True, "active": True}
    ]

    performance_results = {}

    for cfg in configs:
        if not cfg.get("active", True):
            print(f"\nSkipping {cfg['label'].upper()} (disabled)...")
            continue

        prefix = cfg["label"]
        print(f"\n" + "="*50)
        print(f"PROCESSING CONFIG: {prefix.upper()}")
        print("="*50)

        # Capture IR for all stages

        for stage in stages:
            ext = "ll" if stage == "llvm" else "mlir"
            ir_filename = f"{prefix}_{stage}.{ext}"

            cmd = [driver_path, onnx_path, f"-emit={stage}", "-input-files=a.bin,b.bin"]
            if cfg["tiling"]: cmd.append("-tiling")
            if cfg["transpose"]: cmd.append("-transpose")

            print(f"Capturing stage: {stage} -> {ir_filename}")

            try:
                result = subprocess.run(cmd, capture_output=True, text=True, check=True)

                with open(ir_filename, "w") as f:
                    f.write(result.stdout)
            except subprocess.CalledProcessError as e:
                print(f"Error during stage {stage}: {e.stderr}")
    
        # Run JIT
        print(f"Launching JIT for {prefix}")
        jit_cmd = [driver_path, onnx_path, "-emit=jit", "-input-files=a.bin,b.bin"]
        if cfg["tiling"]: jit_cmd.append("-tiling")
        if cfg["transpose"]: jit_cmd.append("-transpose")

        jit_proc = subprocess.run(jit_cmd, capture_output=True, text=True, check=True)

        # Parse Math Time from output
        for line in jit_proc.stdout.split('\n'):
            if "Actual Math Time:" in line:
                print(f"TIMING: {line.strip()}")
                performance_results[prefix] = line.split(":")[1].strip()
            
        # Load JIT result
        if not os.path.exists("output.bin"):
            print("Error: output.bin was not generated by the driver.")
            return
        
        actual = np.fromfile("output.bin", dtype=np.float32)

        if actual.size != expected.size:
            print(f"Error: Size mismatch! Expected {expected.size}, got {actual.size}")
            return

        actual = actual.reshape(expected.shape)

        # Compare elements
        max_diff = np.max(np.abs(actual - expected))
        print("-" * 30)
        print(f"Expected (ORT): {expected.flatten()[:7]}")
        print(f"Actual (JIT): {actual.flatten()[:7]}")
        if max_diff == 0:
            print("RESULT: 100% Bit-Identical Match")
        elif max_diff < 1e-5:
            print(f"RESULT: Perfect Pass (Max Diff: {max_diff:.2e})")
        elif max_diff < 1e-3:
            print(f"RESULT: Acceptable Accumulation Error(Max Diff: {max_diff:.2e})")
            print("Note: Small deltas are expected due to floating-point reassociation.")
        else:
            print(f"RESULT: FAILURE (Max Diff: {max_diff:.2e})")
            print("Check for logic errors or precision loss.")
        print("-" * 30)

    # Final summary
    print("\nSUMMARY: ")
    for label, timing in performance_results.items():
        print(f"{label}: {timing}")

verify_matmul("../../models/onnx_files/matmul_512.onnx", 512, 512, 512)