# RUN: python3 %s

import numpy as np
import onnxruntime as ort
import subprocess
import os

def verify_matmul(onnx_path, m, n, k):
    # Generate data
    a = np.random.randn(m, k).astype(np.float32)
    b = np.random.randn(k, n).astype(np.float32)

    # Save to binary
    a.tofile("a.bin")
    b.tofile("b.bin")

    # Get ORT Ground Truth
    sess = ort.InferenceSession(onnx_path)
    input_names = [i.name for i in sess.get_inputs()]
    expected = sess.run(None, {input_names[0]: a, input_names[1]: b})[0]

    # Run
    use_tiling = False
    stages = ["mlir", "mlir-tensor", "mlir-memref", "mlir-llvm", "llvm", "jit"]
    driver_path = "../../build/driver"

    for stage in stages:
        ext = "ll" if stage == "llvm" else "mlir"
        ir_filename = f"output_{stage}.{ext}"

        cmd = [driver_path, onnx_path, f"-emit={stage}", "-input-files=a.bin,b.bin"]
        if use_tiling:
            cmd.insert(2, "-tiling")

        print(f"Capturing stage: {stage} -> {ir_filename}")

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)

            with open(ir_filename, "w") as f:
                f.write(result.stdout)
        except subprocess.CalledProcessError as e:
            print(f"Error during stage {stage}: {e.stderr}")

    print(f"Launching JIT: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)

    # Load JIT result
    if not os.path.exists("output.bin"):
        print("Error: output.bin was not generated by the driver.")
        return
    
    actual = np.fromfile("output.bin", dtype=np.float32)

    if actual.size != expected.size:
        print(f"Error: Size mismatch! Expected {expected.size}, got {actual.size}")
        return

    actual = actual.reshape(expected.shape)

    # Compare elements
    max_diff = np.max(np.abs(actual - expected))
    print("-" * 30)
    print(f"Expected (ORT): {expected.flatten()[:7]}")
    print(f"Actual (JIT): {expected.flatten()[:7]}")
    if max_diff == 0:
        print("RESULT: 100% Bit-Identical Match")
    elif max_diff < 1e-5:
        print(f"RESULT: Perfect Pass (Max Diff: {max_diff:.2e})")
    elif max_diff < 1e-3:
        print(f"RESULT: Acceptable Accumulation Error(Max Diff: {max_diff:.2e})")
        print("Note: Small deltas are expected due to floating-point reassociation.")
    else:
        print(f"RESULT: FAILURE (Max Diff: {max_diff:.2e})")
        print("Check for logic errors or precision loss.")
    print("-" * 30)

verify_matmul("../../models/onnx_files/matmul_2048.onnx", 2048, 2048, 2048)